import { MigrationInterface, QueryRunner, getRepository } from "typeorm";
import { Branch } from "../entity/Branch";

export class Branches1597474624572 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const data = [
      { region: "NLR", branch: "San Fernando" },
      { region: "NLR", branch: "Dau" },
      { region: "NLR", branch: "Lubao" },
      { region: "NLR", branch: "Tarlac" },
      { region: "NLR", branch: "Olongapo" },
      { region: "NLR", branch: "La Union" },
      { region: "NLR", branch: "Cabanatuan" },
      { region: "NLR", branch: "La Trinidad" },
      { region: "NLR", branch: "Laoag" },
      { region: "NLR", branch: "Vigan" },
      { region: "NLR", branch: "ILAO" },
      { region: "NLR", branch: "PAO" },
      { region: "NLR", branch: "BAO" },
      { region: "NLR", branch: "MAO" },
      { region: "SLR", branch: "Las Pinas" },
      { region: "SLR", branch: "Dasmariñas" },
      { region: "SLR", branch: "General Trias" },
      { region: "SLR", branch: "Imus, Cavite" },
      { region: "SLR", branch: "RAO" },
      { region: "SLR", branch: "San Pablo" },
      { region: "SLR", branch: "Sta. Cruz" },
      { region: "SLR", branch: "Calamba" },
      { region: "SLR", branch: "Palawan" },
      { region: "SLR", branch: "Balayan" },
      { region: "SLR", branch: "Batangas" },
      { region: "SLR", branch: "Lipa" },
      { region: "SLR", branch: "Calapan" },
      { region: "SLR", branch: "San Jose, OM" },
      { region: "SLR", branch: "Iriga" },
      { region: "SLR", branch: "Legazpi" },
      { region: "SLR", branch: "Masbate" },
      { region: "SLR", branch: "Sorsogon" },
      { region: "SLR", branch: "Daet" },
      { region: "SLR", branch: "Gumaca" },
      { region: "SLR", branch: "Lucena" },
      { region: "SLR", branch: "Naga" },
      { region: "SLR", branch: "Sipocot, Camsur" },
      { region: "VIS", branch: "Cebu" },
      { region: "VIS", branch: "Minglanilla" },
      { region: "VIS", branch: "Carcar" },
      { region: "VIS", branch: "Tubigon" },
      { region: "VIS", branch: "Consolacion" },
      { region: "VIS", branch: "Mandaue" },
      { region: "VIS", branch: "Toledo" },
      { region: "VIS", branch: "Tagbilaran" },
      { region: "VIS", branch: "Bogo" },
      { region: "VIS", branch: "Lapu-Lapu" },
      { region: "VIS", branch: "Calbayog" },
      { region: "VIS", branch: "Catarman" },
      { region: "VIS", branch: "Maasin" },
      { region: "VIS", branch: "Ormoc" },
      { region: "VIS", branch: "Tacloban" },
      { region: "VIS", branch: "Bacolod" },
      { region: "VIS", branch: "Dumaguete" },
      { region: "VIS", branch: "Bais" },
      { region: "VIS", branch: "San Carlos" },
      { region: "VIS", branch: "Iloilo" },
      { region: "VIS", branch: "Roxas" },
      { region: "VIS", branch: "Kalibo" },
      { region: "NMR", branch: "Dipolog" },
      { region: "NMR", branch: "Ozamis" },
      { region: "NMR", branch: "Ipil" },
      { region: "NMR", branch: "Oroquieta" },
      { region: "NMR", branch: "Pagadian" },
      { region: "NMR", branch: "Molave" },
      { region: "NMR", branch: "Zamboanga" },
      { region: "NMR", branch: "CDO Corrales" },
      { region: "NMR", branch: "Iligan" },
      { region: "NMR", branch: "Maranding" },
      { region: "NMR", branch: "Valencia" },
      { region: "NMR", branch: "Don Carlos" },
      { region: "NMR", branch: "Malaybalay" },
      { region: "NMR", branch: "CDO Cugman" },
      { region: "NMR", branch: "CDO Iponan" },
      { region: "NMR", branch: "Surigao" },
      { region: "NMR", branch: "Gingoog" },
      { region: "NMR", branch: "Butuan" },
      { region: "NMR", branch: "Bayugan" },
      { region: "NMR", branch: "Cabadbaran" },
      { region: "EMR", branch: "San Francisco" },
      { region: "EMR", branch: "Barobo" },
      { region: "EMR", branch: "Trento" },
      { region: "EMR", branch: "Tandag" },
      { region: "EMR", branch: "Nabunturan" },
      { region: "EMR", branch: "Bislig" },
      { region: "EMR", branch: "Mati" },
      { region: "EMR", branch: "Panabo" },
      { region: "EMR", branch: "Tagum" },
      { region: "EMR", branch: "Carmen" },
      { region: "EMR", branch: "Lupon" },
      { region: "EMR", branch: "Toril" },
      { region: "EMR", branch: "Calinan" },
      { region: "EMR", branch: "Davao" },
      { region: "EMR", branch: "Matina" },
      { region: "SMR", branch: "Digos" },
      { region: "SMR", branch: "Malita" },
      { region: "SMR", branch: "Bansalan" },
      { region: "SMR", branch: "Kidapawan" },
      { region: "SMR", branch: "Antipas" },
      { region: "SMR", branch: "General Santos" },
      { region: "SMR", branch: "Calumpang" },
      { region: "SMR", branch: "Koronadal" },
      { region: "SMR", branch: "San Isidro" },
      { region: "SMR", branch: "Surallah" },
      { region: "SMR", branch: "Polomolok" },
      { region: "SMR", branch: "Midsayap" },
      { region: "SMR", branch: "Lebak" },
      { region: "SMR", branch: "M'lang" },
      { region: "SMR", branch: "Kabacan" },
      { region: "SMR", branch: "Tacurong" },
      { region: "SMR", branch: "Isulan" },
    ];

    const repo = getRepository(Branch);
    await repo.save(data);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
